tap "fabianishere/personal"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "sanemat/font"
brew "python@3.9", link: false
brew "ansible"
brew "automake"
brew "boost-python"
brew "cmake"
brew "cpanminus"
brew "ctags"
brew "direnv"
brew "docker"
brew "fontforge"
brew "fzf"
brew "git-lfs"
brew "go"
brew "grep"
brew "helm"
brew "helmfile"
brew "htop"
brew "imagemagick"
brew "jq"
brew "kubernetes-cli", link: false
brew "libevent"
brew "libiconv"
brew "libxml2"
brew "libxslt"
brew "lua"
brew "luajit"
brew "luarocks"
brew "mercurial"
brew "mysql"
brew "neovim", args: ["HEAD"]
brew "nkf"
brew "peco"
brew "pstree"
brew "q"
brew "ruby-build"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rmtrash"
brew "ruby"
brew "rust"
brew "ssh-copy-id", link: true
brew "tig"
brew "tmux"
brew "vim"
brew "w3m"
brew "wget"
brew "yarn"
brew "zlib"
brew "zsh"
brew "sanemat/font/ricty"
cask "alfred"
cask "appcleaner"
cask "caffeine"
cask "dropbox"
cask "firefox"
cask "flux"
cask "gimp"
cask "google-chrome"
cask "google-japanese-ime"
cask "growlnotify"
cask "iterm2"
cask "karabiner-elements"
cask "keyboardcleantool"
cask "slack"
cask "the-unarchiver"
cask "vagrant"
cask "virtualbox"
cask "vlc"
cask "xquartz"
mas "1Password", id: 443987910
mas "BetterSnapTool", id: 417375580
mas "Growl", id: 467939042
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PicGIF Lite", id: 844918735
mas "Xcode", id: 497799835
