tap "daipeihust/tap"
tap "fabianishere/personal"
tap "harelba/q"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "sanemat/font"
tap "universal-ctags/universal-ctags"
brew "automake"
brew "cmake"
brew "coreutils"
brew "curl"
brew "direnv"
brew "fontforge"
brew "fzf"
brew "git"
brew "git-lfs"
brew "go"
brew "python@3.9"
brew "grep"
brew "helm"
brew "helmfile"
brew "ncurses"
brew "htop"
brew "python@3.8"
brew "imagemagick"
brew "jq"
brew "libevent"
brew "libiconv"
brew "libxml2"
brew "libxslt"
brew "lua"
brew "luajit"
brew "luarocks"
brew "mas"
brew "zlib"
brew "mysql"
brew "neovim"
brew "nkf"
brew "peco"
brew "pstree"
brew "ruby-build"
brew "rbenv"
brew "ripgrep"
brew "rust"
brew "stern"
brew "telnet"
brew "tig"
brew "tmux"
brew "tmux-mem-cpu-load"
brew "tree"
brew "vim"
brew "w3m"
brew "wget"
brew "yarn"
brew "zsh"
brew "daipeihust/tap/im-select"
brew "harelba/q/q"
brew "hashicorp/tap/terraform"
brew "sanemat/font/ricty"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "alfred"
cask "appcleaner"
cask "caffeine"
cask "dropbox"
cask "fig"
cask "firefox"
cask "flux"
cask "google-chrome"
cask "google-japanese-ime"
cask "growlnotify"
cask "iterm2"
cask "karabiner-elements"
cask "keyboardcleantool"
cask "slack"
cask "the-unarchiver"
cask "vagrant"
cask "vlc"
cask "xquartz"
mas "BetterSnapTool", id: 417375580
mas "GarageBand", id: 682658836
mas "Growl", id: 467939042
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
