ln -s $HOME/dotfiles/.emacs.el $HOME/.emacs.el
ln -s $HOME/dotfiles/.screenrc $HOME/.screenrc
ln -s $HOME/dotfiles/.zshrc $HOME/.zshrc
ln -s $HOME/dotfiles/.zsh $HOME/.zsh
ln -s $HOME/dotfiles/.gitignore $HOME/.gitignore
ln -s $HOME/dotfiles/.gdbinit $HOME/.gdbinit
ln -s $HOME/dotfiles/.vim $HOME/.vim
ln -s $HOME/dotfiles/.vimrc $HOME/.vimrc
ln -s $HOME/dotfiles/import.scala $HOME/import.scala
ln -s $HOME/dotfiles/.vrapperrc $HOME/.vrapperrc
ln -s $HOME/dotfiles/.gitconfig $HOME/.gitconfig
