#!/usr/bin/env bash

while :
do
  read -p "install dotfiles? y/n " yn
  if [ $yn = "n" -o $yn = "N" ]; then
    exit
  elif [ $yn = "y" -o $yn = "Y" ]; then
    break
  else
    continue
  fi
done

ORIGIN=$(pwd)
DOTFILES_PATH=$HOME/dotfiles
INSTALLER_PATH=$DOTFILES_PATH/bin/installer

PKGS=(
  ricty-diminished
  tmux-256color
  tmux-powerline
)
for pkg in ${PKGS[@]}
do
  $INSTALLER_PATH/$pkg-installer
done

DIRS=(
  .cache
  .config/nvim
  .config/powerline-shell
  .vim
)
for dir in ${DIRS[@]}
do
  mkdir -p $HOME/$dir
done

DOTFILES=(
  .agignore
  .dir_colors
  .gemrc
  .gitconfig
  .gitignore
  .inputrc
  .irbrc
  .pryrc
  .rdebugrc
  .ripgreprc
  .rspec
  .rubocop.yml
  .tmux-powerlinerc
  .tmux.conf
  .tmuxinator
  .vim/dict
  .config/nvim/init.vim
  .config/powerline-shell/config.json
  .vimrc
  .zshrc
)
for file in ${DOTFILES[@]}
do
  ln -sf $DOTFILES_PATH/$file $HOME/$file
done

# NeoBundle
# . $INSTALLER_PATH/neobundle-installer

# dein
$INSTALLER_PATH/dein-installer

cd ${ORIGIN}
exec $SHELL
