#!/usr/bin/env bash

while :
do
  read -p "install dotfiles? y/n " yn
  if [ $yn = "n" -o $yn = "N" ]; then
    exit
  elif [ $yn = "y" -o $yn = "Y" ]; then
    break
  else
    continue
  fi
done

ORIGIN=$(pwd)
DOTFILES_PATH=$HOME/dotfiles
INSTALLER_PATH=$DOTFILES_PATH/bin/installer

PKGS=(
  ricty auto-fu
  powerline-shell
  tmux-powerline
  tmux-mem-cpu-load
  tmuxinator )
for pkg in ${PKGS[@]}
do
  $INSTALLER_PATH/$pkg-installer
done

DIRS=( .vim .config/zathura )
for dir in ${DIRS[@]}
do
  mkdir -p $HOME/$dir
done

DOTFILES=(
  .zshrc .ctags .gdbinit .gemrc
  .gitconfig .gitignore .inputrc
  .irbrc .pryrc .rspec .agignore
  .vimrc .vrapperrc .rubocop.yml
  .tmux.conf .tmux-powerlinerc .splintrc
  .dir_colors .rdebugrc .vim/dict
  .config/zathura/zathurarc )
for file in ${DOTFILES[@]}
do
  ln -sf $DOTFILES_PATH/$file $HOME/$file
done

# NeoBundle
$INSTALLER_PATH/neobundle-installer

cd ${ORIGIN}
exec $SHELL
