#!/usr/bin/env bash

while :
do
  read -p 'uninstall dotfiles? y/n ' yn
  if [ $yn = 'n' -o $yn = 'N' ]; then
    exit
  elif [ $yn = 'y' -o $yn = 'Y' ]; then
    break
  else
    continue
  fi
done

UNINSTALLER_PATH=$HOME/dotfiles/bin/uninstaller

PKGS=(
  tmux-powerline
)
for pkg in ${PKGS[@]}
do
  $UNINSTALLER_PATH/$pkg-uninstaller
done

DOTFILES=(
  .gemrc
  .gitconfig
  .gitignore
  .inputrc
  .irbrc
  .nodenv/default-packages
  .pryrc
  .rbenv/default-gems
  .rdebugrc
  .ripgreprc
  .rspec
  .rubocop.yml
  .tmux-powerlinerc
  .tmux.conf
  .tmuxinator
  .vim/dict
  .config/alacritty/alacritty.yml
  .config/nvim/init.vim
  .config/peco/config.json
  .vimrc
  .zshrc
  .wezterm.lua
)
for file in ${DOT_FILES[@]}
do
  if [ -f $HOME/$file ]; then
    rm -rf $HOME/$file
  fi
done

exec $SHELL
