#!/usr/bin/env bash

while :
do
  read -p "uninstall dotfiles? y/n " yn
  if [ $yn = "n" -o $yn = "N" ]; then
    exit
  elif [ $yn = "y" -o $yn = "Y" ]; then
    break
  else
    continue
  fi
done

UNINSTALLER_PATH=$HOME/dotfiles/bin/uninstaller

PKGS=(
  ricty
)
for pkg in ${PKGS[@]}
do
  $UNINSTALLER_PATH/$pkg-uninstaller
done

DOTFILES=(
  .agignore
  .dir_colors
  .gdbinit
  .gemrc
  .gitconfig
  .gitignore
  .inputrc
  .irbrc
  .pryrc
  .rdebugrc
  .rspec
  .rubocop.yml
  .tmux-powerlinerc
  .tmux.conf
  .vim/dict
  .config/nvim/init.vim
  .config/powerline-shell/config.json
  .vimrc
  .zshrc
)
for file in ${DOT_FILES[@]}
do
  if [ -f $HOME/$file ]; then
    rm -rf $HOME/$file
  fi
done

exec $SHELL
