#!/usr/bin/env bash

while :
do
  read -p "uninstall dotfiles? y/n " yn
  if [ $yn = "n" -o $yn = "N" ]; then
    exit
  elif [ $yn = "y" -o $yn = "Y" ]; then
    break
  else
    continue
  fi
done

UNINSTALLER_PATH=$HOME/dotfiles/bin/uninstaller

PKGS=(
  ricty
  vvm-rb auto-fu
  powerline-shell
  tmux-powerline
  tmux-mem-cpu-load
  tmuxinator )
for pkg in ${PKGS[@]}
do
  $UNINSTALLER_PATH/$pkg-uninstaller
done

DOT_FILES=(
  .zshrc .zshenv .ctags .gdbinit .gemrc
  .gitconfig .gitignore .inputrc
  .irbrc .pryrc .rspec .agignore
  .vimrc .vrapperrc .rubocop.yml
  .tmux.conf .tmux-powerlinerc .splintrc
  .dir_colors .rdebugrc .vim/dict dotfiles )

for file in ${DOT_FILES[@]}
do
  rm -rf $HOME/$file
done

exec $SHELL
