#!/usr/bin/env bash

while :
do
  read -p "update? y/n " yn
  if [ $yn = "n" -o $yn = "N" ]; then
    exit
  elif [ $yn = "y" -o $yn = "Y" ]; then
    break
  else
    continue
  fi
done

ORIGIN=$(pwd)

# rubygems
if command -v update_rubygems >/dev/null 2>&1; then
  update_rubygems
fi

# tmuxinator
if command -v mux >/dev/null 2>&1; then
  gem install tmuxinator
fi

# tmux-mem-cpu-load
if [ -d $HOME/.tmux/tmux-mem-cpu-load ]; then
  cd $HOME/.tmux/tmux-mem-cpu-load
  git reset --hard HEAD
  git clean -fd
  git pull --rebase origin master
  sed -i -e "s/ << ' ' << load_string( use_colors )//" $HOME/.tmux/tmux-mem-cpu-load/tmux-mem-cpu-load.cpp
  cmake .
  make
  sudo make install
fi

# tmux-powerline
if [ -d $HOME/.tmux/tmux-powerline ]; then
  cd $HOME/.tmux/tmux-powerline
  git pull --rebase origin master
fi

# auto-fu
if [ -d $HOME/.zsh/auto-fu.zsh ]; then
  cd $HOME/.zsh/auto-fu.zsh
  git pull --rebase origin pu
fi

# powerline-shell
if [ -d $HOME/.zsh/powerline-shell ]; then
  cd $HOME/.zsh/powerline-shell
  git stash -u
  git pull --rebase origin master
  git stash pop
  ./install.py
fi

# rbenv
if [ -d $RBENV_ROOT/plugins/rbenv-update ]; then
  rbenv update
fi

# vim plugins
if command -v vim >/dev/null 2>&1; then
  vim +NeoBundleUpdate +qa
fi

cd ${ORIGIN}
exec $SHELL
