#!/usr/bin/env bash

while :
do
  read -p 'update? y/n ' yn
  if [ $yn = 'n' -o $yn = 'N' ]; then
    exit
  elif [ $yn = 'y' -o $yn = 'Y' ]; then
    break
  else
    continue
  fi
done

ORIGIN=$(pwd)

# rubygems
if command -v update_rubygems >/dev/null 2>&1; then
  update_rubygems
fi

gem update
npm update -g
pip install -r $HOME/dotfiles/requirements.txt --upgrade

# tmux-powerline
if [ -d $HOME/.tmux/tmux-powerline ]; then
  cd $HOME/.tmux/tmux-powerline
  git pull --rebase origin main
fi

# enhancd
if [ -d $HOME/enhancd ]; then
  cd $HOME/enhancd
  git pull --rebase origin master
fi

# nvim plugins
if command -v nvim >/dev/null 2>&1; then
  nvim +':silent call dein#update()' +qa
fi

cd ${ORIGIN}
exec $SHELL
